# Generated by Django 4.2.6 on 2023-11-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorder',
            name='CategoryId',
            field=models.IntegerField(blank=True, null=True, verbose_name='Category ID'),
        ),
    ]
